services:
  proxy:
    image: traefik:latest
    container_name: "traefik"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/proxy/traefik.yml:/traefik.yml:ro
      - ./conf/proxy/traefik-dynamic-config.yml:/traefik-dynamic-config.yml:ro
      - ~/ssl/acme.json:/acme.json
    networks:
      - frontend
      - backend
  cloudanytechteam:
    build: ./container/cloud.anytech.tech
    image: anytech.team:latest
    volumes:
      - /root/docker/data/anytech.team-data:/opt/nextcloud-data
    env_file:
      - .env
    links:
      - centraldb
      - redis
      - proxy:office.anytech.team
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=backend"
      - "traefik.http.routers.cloudanytechteam.rule=Host(`anytech.team`)"
      - "traefik.http.routers.cloudanytechteam.entrypoints=websecure"
      - "traefik.http.routers.cloudanytechteam.tls.certresolver=leresolver"
      - "traefik.http.routers.cloudanytechteam.middlewares=default@file"
      - "traefik.http.routers.cloudanytechteam.middlewares=nextcloud_redirectregex"
      - "traefik.http.services.cloudanytechteam.loadbalancer.server.port=80"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex='https://(.*)/.well-known/(?:card|cal)dav'"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement='https://$${1}/remote.php/dav'"
    networks:
      - backend
  centraldb:
    build: ./container/centraldb
    volumes:
      - /root/docker/data/anytech.team-postgresdata:/var/lib/postgresql/data
      - /root/docker/data/anytech.team-database:/opt/backup
    env_file:
      - .env
    networks:
      - backend
  nextcloud:
    build: ./container/nextcloud
    image: nextcloud:latest
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: >
      /bin/sh -c 'redis-server --appendonly yes --requirepass $$REDIS_PASSWORD'
    env_file:
      - .env
    networks:
      - backend

  collabora:
    image: collabora/code:latest
    restart: unless-stopped
    container_name: collabora
    cap_add:
      - MKNOD
    links:
      - proxy:anytech.team
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=backend"
      - "traefik.http.routers.collabora.rule=Host(`office.anytech.team`)"
      - "traefik.http.routers.collabora.entrypoints=websecure"
      - "traefik.http.routers.collabora.middlewares=collaboraHeaders@file"
      - "traefik.http.routers.collabora.tls.certresolver=leresolver"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"
    networks:
      - backend
networks:
  frontend:
    internal: false
  backend:
    internal: true
