log:
  level: WARN

api:
  dashboard: false
providers:
  docker:
    network: backend
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    filename: "/traefik-dynamic-config.yml"
    watch: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
          permanent: true
  websecure:
    address: ":443"
  streaming:
    address: ":64738/udp"
    udp:
      timeout: "10s"
  other:
    address: ":64738"
certificatesResolvers:
  leresolver:
    acme:
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      email: "ssl@anytech.team"
      storage: "/acme.json"
      httpChallenge:
        entrypoint: web