http:
  middlewares:
    default:
      chain:
        middlewares:
          - secureHeaders
    defaultWithOriginReferrer:
      chain:
        middlewares:
          - originReferrer
          - secureHeaders
    secureHeaders:
      headers:
        referrerPolicy: "no-referrer"
        featurePolicy: "geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; fullscreen 'self'; payment 'none'"
        sslTemporaryRedirect: true
        sslForceHost: true
        customFrameOptionsValue: "SAMEORIGIN"
        addVaryHeader: true
        sslRedirect: true
        frameDeny: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: "31536000"
        contentTypeNosniff: true
        accessControlMaxAge: "31536000"
        accessControlAllowOriginList: "https://symbiolab.de, https://*.symbiolab.de
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
        accessControlAllowMethods: "GET, POST, PUT, DELETE, PROPFIND, HEAD"
    originReferrer:
      headers:
        referrerPolicy: "origin"
    collaboraHeaders:
      headers:
        customResponseHeaders:
          user-agent: "<deleted>"
          x-content-type-options: ""
          x-xss-protection: ""
          referrer-policy: ""
          content-security-policy: ""
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        # ciphers for TLSv1.2
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        # ciphers for TLSv1.3
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    tlsv13only:
      minVersion: VersionTLS13
    modern:
      minVersion: "VersionTLS13" 
      sniStrict: true
